// Depo ve lokasyon alanı (T-205): kart komutları, ağaç okuyucuları, depo kapsamı denetimi.
export {
  archiveWarehouse,
  createWarehouse,
  getWarehouse,
  listWarehouses,
  normalizeCode,
  normalizeName,
  renameWarehouse,
  type ArchiveWarehouseInput,
  type CreateWarehouseInput,
  type ListWarehousesInput,
  type ListWarehousesResult,
  type RenameWarehouseInput,
  type WarehouseCallParams,
  type WarehouseRow,
} from "./warehouses.ts";
export {
  MAX_LOCATION_DEPTH,
  COUNT_WAREHOUSES_MAX,
  archiveLocation,
  childDepth,
  countLocationsByWarehouse,
  createLocation,
  findLocationByCode,
  getLocationTree,
  renameLocation,
  setLocationKind,
  type ArchiveLocationInput,
  type CountLocationsByWarehouseInput,
  type CreateLocationInput,
  type GetLocationTreeInput,
  type LocationKindValue,
  type LocationRow,
  type LocationTreeCursor,
  type LocationTreePage,
  type RenameLocationInput,
  type SetLocationKindInput,
} from "./locations.ts";
export {
  WAREHOUSE_SCOPE_FLAG,
  assertWarehouseInScope,
  assertWarehouseVisible,
  isWarehouseScopeEnabled,
  resolveWarehouseScope,
  setMembershipWarehouseScopes,
  type SetScopesInput,
  type SetScopesResult,
} from "./scope.ts";
export {
  BULK_LOCATIONS_MAX,
  IDEMPOTENCY_WINDOW_DAYS,
  createBulkLocations,
  planBulkLocations,
  previewBulkLocations,
  type BulkCreateResult,
  type BulkLocationsSpec,
  type BulkPlan,
  type BulkPreview,
  type CreateBulkLocationsInput,
} from "./bulk-locations.ts";
export {
  LOCATION_SEARCH_MAX,
  getSetupProgress,
  searchLocations,
  type LocationSuggestion,
  type SearchLocationsInput,
  type SetupProgress,
} from "./setup-queries.ts";
